Develop
rgrumbine/concentration pull request #28
Opened 2024-08-19 17:09 UTC by rgrumbine

This removes legacy code for SSMI (last instrument failed years ago) and developmental code (directory 'filter') for weather filtering. Fortran updates to rigorous Fortran-90 standard, mostly to F-95 or better.

GEMPAK and notes for operations are brought back in to the repository.

There are various minor evolutions in the code/scripts. And there are some pre-adaptations for eventual building by cmake. The authoritative process, though, remains makeall.sh in the sorc directory.

2024-08-20 00:59 UTC, sanAkel commented
@rgrumbine,
I'll get back on this early next (on annual leave this week).

2024-09-04 22:00 UTC, sanAkel commented on sorc/amsr2/seaice_amsrbufr.fd/makefile
> +#LIBS = ${W3EMC_LIBd} ${BUFR_LIBd} ${BACIO_LIB4}
Rather than commenting old lines, please delete them; repo/git can help us track new/old versions.

2024-09-04 22:01 UTC, sanAkel commented on sorc/amsr2/seaice_iceamsr2.Cd/makefile
> +#LIBS = ${W3EMC_LIBd} ${BUFR_LIBd} ${BACIO_LIB4}
Please remove commented line

2024-09-04 22:04 UTC, sanAkel commented on sorc/general/seaice_grib2.fd/CMakeLists.txt
Why is the file empty? We can add it later as part of `CMake` clean up/fixes.

2024-09-04 22:12 UTC, sanAkel requested changes
Few minor changes are suggested. Thanks for patiently waiting for my review.

2024-09-26 12:42 UTC, rgrumbine commented on sorc/general/seaice_grib2.fd/CMakeLists.txt
It's a reminder that the file needs to be filled in. This is a style point from the fact I often go long stretches without working on the system, so this is a reminder that this is something I still need to work on, whenever it is I next do so. Since you're actively working on this, there's no need for my reminder.

2024-09-27 12:56 UTC, sanAkel approved these changes
All suggestion/requested changes seems to have been accepted/done.

Thanks @rgrumbine

2024-09-27 12:59 UTC, merged